#!/usr/bin/env sh
set -e

OUTPUT_FILE="nginx/cloudflare.conf"

echo "=========================================="
echo "Fetching Cloudflare Public IP Ranges..."
echo "=========================================="

# Create the file with basic headers
cat <<EOF > "$OUTPUT_FILE"
# Cloudflare Real IP Configuration
# Automatically generated by scripts/cloudflare_ips.sh

real_ip_header CF-Connecting-IP;
real_ip_recursive on;

EOF

# Fetch IPv4 ranges
echo "Retrieving IPv4 addresses..."
curl -s https://www.cloudflare.com/ips-v4 | while read -r ip; do
    if [ -n "$ip" ]; then
        echo "set_real_ip_from $ip;" >> "$OUTPUT_FILE"
    fi
done

# Fetch IPv6 ranges
echo "Retrieving IPv6 addresses..."
curl -s https://www.cloudflare.com/ips-v6 | while read -r ip; do
    if [ -n "$ip" ]; then
        echo "set_real_ip_from $ip;" >> "$OUTPUT_FILE"
    fi
done

echo "Cloudflare IPs successfully written to $OUTPUT_FILE!"
