#!/usr/bin/env python3
import urllib.request
import os

def main():
    output_path = os.path.join("nginx", "cloudflare.conf")
    print("==========================================")
    print("Fetching Cloudflare Public IP Ranges...")
    print("==========================================")
    
    try:
        # Fetch IPv4
        print("Retrieving IPv4 addresses...")
        req = urllib.request.Request("https://www.cloudflare.com/ips-v4", headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            ipv4_data = response.read().decode('utf-8').splitlines()
        
        # Fetch IPv6
        print("Retrieving IPv6 addresses...")
        req = urllib.request.Request("https://www.cloudflare.com/ips-v6", headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response:
            ipv6_data = response.read().decode('utf-8').splitlines()
            
        # Write to file
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write("# Cloudflare Real IP Configuration\n")
            f.write("# Automatically generated by scripts/cloudflare_ips.py\n\n")
            f.write("real_ip_header CF-Connecting-IP;\n")
            f.write("real_ip_recursive on;\n\n")
            
            for ip in ipv4_data:
                if ip.strip():
                    f.write(f"set_real_ip_from {ip.strip()};\n")
            
            for ip in ipv6_data:
                if ip.strip():
                    f.write(f"set_real_ip_from {ip.strip()};\n")
                    
        print(f"Cloudflare IPs successfully written to {output_path}!")
    except Exception as e:
        print(f"Error fetching Cloudflare IPs: {e}")

if __name__ == "__main__":
    main()
